#!/bin/sh
# Script to send current volume notification to dunstify 
# need depencies pamixer, dunstify and canberra-gtk-play for sound
# add this script to you volume control bind
msgID="2345"
mute="$(pamixer --get-mute)"
 

# check volume
if [ "$mute" == "true" ]; then
	dunstify  "  Muted " -t 800 -r $msgID
else
	dunstify  "  Unmuted" -t 800 -r $msgID

fi


